-- MySQL Script generated by MySQL Workbench
-- dom 05 abr 2020 13:01:08 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema supera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supera` DEFAULT CHARACTER SET utf8 ;
USE `supera` ;

-- -----------------------------------------------------
-- Table `supera`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supera`.`usuario` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supera`.`ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supera`.`ferramenta` (
  `id_ferramenta` VARCHAR(45) NOT NULL,
  `id_dono` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor_dia` FLOAT NOT NULL,
  `vezes_alugada` INT NOT NULL,
  PRIMARY KEY (`id_ferramenta`, `id_dono`),
  INDEX `fk_ferramenta_1_idx` (`id_dono` ASC) VISIBLE,
  CONSTRAINT `fk_ferramenta_1`
    FOREIGN KEY (`id_dono`)
    REFERENCES `supera`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supera`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `supera`.`aluguel` (
  `id_aluguel` VARCHAR(45) NOT NULL,
  `dono_id` VARCHAR(45) NOT NULL,
  `ferramenta_id` VARCHAR(45) NOT NULL,
  `nome_beneficiado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aluguel`, `dono_id`, `ferramenta_id`),
  INDEX `fk_Usuário_has_Ferramenta_Ferramenta1_idx` (`ferramenta_id` ASC) VISIBLE,
  INDEX `fk_Usuário_has_Ferramenta_Usuário1_idx` (`dono_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_has_Ferramenta_Usuário1`
    FOREIGN KEY (`dono_id`)
    REFERENCES `supera`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuário_has_Ferramenta_Ferramenta1`
    FOREIGN KEY (`ferramenta_id`)
    REFERENCES `supera`.`ferramenta` (`id_ferramenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
